config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Default routes 
  get "home", to: "home#index"
  get "contact", to: "contact#index"
  get "users", to: "users#index"

  # Users routes 
  get "users/new", to: "users#new"
  get "users/:id", to: "users#show"
  post "users", to: "users#create"
  get "users/:id/edit", to: "users#edit"
  patch "users/:id", to: "users#update"
  delete "users/:id", to: "users#destroy"

  # Resources for the users controller
  # resources :users
  
  # Users routes
  # get "/signup",  to: "users#new"
  # get "/login",   to: "sessions#new"
  # post "/login",   to: "sessions#create"
  # delete "/logout",  to: "sessions#destroy"

  namespace :admin do
    resources :posts

    root to: "posts#index"
  end
  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/user_controller.rb
class User < ApplicationRecord
end

app/controllers/admin/application_controller.rb
module Admin
    class ApplicationController < Administrate::ApplicationController
        before_action :authenticate_admin
        def authenticate_admin
            # TODO Add authentication logic here.
        end
    end
end

app/controllers/admin/posts_controller.rb
module Admin
    class PostsController < Admin::ApplicationController
        def index
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    def index 
    end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def index
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_me] == '1' ? remember(user) : forget(user)
        redirect_back_or user
      else
        message  = "Account not activated. "
        message += "Check your email for the activation link."
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ActiveRecord::Migration[5.2]
    def index
    end

    def new
    end
    
    def change
        create_table :dogs do |t|
        t.string :name
        t.string :motto
        
        t.timestamps
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contact/index.html.erb
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= stylesheet_link_tag 'forms', media: 'all' %>
<link href="https://fonts.googleapis.com/css?family=Inter:400,400italic,300,300italic%7CEl+Messiri:400,400italic%7CLato:400,400italic" rel="stylesheet" type="text/css" />

<main>

    <div id="contact">
        <h1 class="title style1">Keep in touch</h1>

        <form method="GET" id="contact_form" action="http://localhost:3000/">
            <div class="form-group">
                <label class="input">
                    <input class="input__field" type="text" name="contact_name" id="contact_name" placeholder=" " maxlength="20"/>
                    <span class="input__label">Your name</span>
                </label>

                <label class="input">
                    <input class="input__field" type="text" name="contact_name" id="contact_name" placeholder=" " maxlength="20"/>
                    <span class="input__label">Phone number</span>
                </label>

                <label class="input">
                    <input class="input__field" type="text" name="contact_name" id="contact_name" placeholder=" " maxlength="20"/>
                    <span class="input__label">Email</span>
                </label>
            </div>

            <div class="form-group">
                <input type="submit" name="submit" id="submit" value="Send message" />
                <input type="reset" name="reset" id="reset" value="Reset fields" />
            </div>
        </form>

    </div>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ruby Fitness Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

app/views/posts/index.html.erb
<main>
    <h1>Posts</h1>

    <%= link_to "New post", new_post_path %>
</main>

<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/posts/new.html.erb
<h1>New post</h1>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= stylesheet_link_tag 'forms', media: 'all' %>
<%= stylesheet_link_tag 'user', media: 'all' %>
<link href="https://fonts.googleapis.com/css?family=Inter:400,400italic,300,300italic%7CEl+Messiri:400,400italic%7CLato:400,400italic" rel="stylesheet" type="text/css" />

<main>

    <div id="login">
        <h1 class="title style1">Login page</h1>

        <form method="GET" id="contact_form" action="http://localhost:3000/">
            <div class="form-group">
                <label class="input">
                    <input class="input__field" type="email" name="contact_name" id="contact_name" placeholder=" " maxlength="20"/>
                    <span class="input__label">Email</span>
                </label>

                <label class="input">
                    <input class="input__field" type="password" name="contact_name" id="contact_name" placeholder=" " maxlength="20"/>
                    <span class="input__label">Password</span>
                </label>
            </div>

            <div class="form-group">
                <input type="submit" name="submit" id="submit" value="Confirm" />
                <input type="reset" name="reset" id="reset" value="Forgot password" />
            </div>
        </form>

    </div>

</main>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:button_text, 'Create my account') %>
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= stylesheet_link_tag 'forms', media: 'all' %>
<link href="https://fonts.googleapis.com/css?family=Inter:400,400italic,300,300italic%7CEl+Messiri:400,400italic%7CLato:400,400italic" rel="stylesheet" type="text/css" />



  <div id="signup">
      <h1 class="title style1">Sign up</h1>

      <form method="GET" id="contact_form" action="http://localhost:3000/">
          <div class="form-group">
              <label class="input">
                  <input class="input__field" type="text" name="contact_name" id="contact_name" placeholder=" " maxlength="20"/>
                  <span class="input__label">Email</span>
              </label>

              <label class="input">
                  <input class="input__field" type="password" name="contact_name" id="contact_name" placeholder=" " maxlength="20"/>
                  <span class="input__label">Password</span>
              </label>
          </div>

          <div class="form-group">
              <input type="submit" name="submit" id="submit" value="Send message" />
              <input type="reset" name="reset" id="reset" value="Reset fields" />
          </div>
      </form>
  </div>
</div>